"""update product modele

Revision ID: 1f01868f5d85
Revises: 53a7f89b5595
Create Date: 2026-03-29 19:09:29.974838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f01868f5d85'
down_revision: Union[str, Sequence[str], None] = '53a7f89b5595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'tsv',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'tsv',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
