"""empty message

Revision ID: 45dcbdc5ecf1
Revises: 743d3c707f8d
Create Date: 2026-03-24 13:32:22.399292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45dcbdc5ecf1'
down_revision: Union[str, Sequence[str], None] = '743d3c707f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'comment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('reviews', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('reviews', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('reviews', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('reviews', 'comment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
